const {chromium}=require('C:/Users/asus/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'); const path=require('path');
const out=path.join(__dirname,'evidence');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,recordHar:{path:path.join(out,'desktop.har'),content:'omit'}});
 const page=await context.newPage(); const requests=[],errors=[];
 page.on('response',async r=>{requests.push({url:r.url(),status:r.status(),type:r.request().resourceType(),headers:await r.allHeaders()}); if(/www\.igloo\.inc\/assets\/.*\.(js|css)(\?|$)/.test(r.url())){try{fs.writeFileSync(path.join(out,new URL(r.url()).pathname.split('/').pop()),await r.body())}catch{}}});
 page.on('console',m=>errors.push({type:m.type(),text:m.text()}));page.on('pageerror',e=>errors.push({type:'pageerror',text:e.message}));
 await page.addInitScript(()=>{window.__inspection={events:[],contexts:[]}; const orig=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...args){const r=orig.call(this,t,...args); if(r&&!window.__inspection.contexts.some(x=>x.ctx===r))window.__inspection.contexts.push({type:t,ctx:r,canvas:this,attrs:args});return r}; const listen=EventTarget.prototype.addEventListener; EventTarget.prototype.addEventListener=function(type,fn,opt){if(['wheel','touchstart','touchmove','pointermove','keydown','click','resize'].includes(type))window.__inspection.events.push({target:this===window?'window':this===document?'document':this.tagName||this.constructor.name,type,options:opt}); return listen.call(this,type,fn,opt)};});
 const client=await context.newCDPSession(page);await client.send('Performance.enable');await client.send('Network.enable');
 const nav=await page.goto('https://www.igloo.inc/',{waitUntil:'domcontentloaded',timeout:60000}); console.log('NAV',nav.status());
 await page.screenshot({path:path.join(out,'desktop-01-loading.png')});
 await page.waitForTimeout(18000);await page.screenshot({path:path.join(out,'desktop-02-entry.png')});
 async function state(label){const data=await page.evaluate(()=>({url:location.href,title:document.title,text:document.body.innerText,html:document.documentElement.outerHTML,scroll:{y:scrollY,height:document.documentElement.scrollHeight,bodyHeight:document.body.scrollHeight},globals:Object.keys(window).filter(k=>/three|gsap|svelte|scroll|app|spector/i.test(k)),fonts:[...document.fonts].map(f=>({family:f.family,status:f.status})),elements:[...document.querySelectorAll('canvas,a,button,input,video,audio')].map(e=>({tag:e.tagName,id:e.id,class:e.className,href:e.href,text:e.textContent,rect:e.getBoundingClientRect().toJSON(),css:{position:getComputedStyle(e).position,zIndex:getComputedStyle(e).zIndex,pointerEvents:getComputedStyle(e).pointerEvents}})),events:window.__inspection.events,gl:window.__inspection.contexts.filter(x=>/webgl/.test(x.type)).map(x=>{let gl=x.ctx;let ext=gl.getExtension('WEBGL_debug_renderer_info');return{type:x.type,canvas:{width:x.canvas.width,height:x.canvas.height},attrs:gl.getContextAttributes(),version:gl.getParameter(gl.VERSION),vendor:ext&&gl.getParameter(ext.UNMASKED_VENDOR_WEBGL),renderer:ext&&gl.getParameter(ext.UNMASKED_RENDERER_WEBGL),maxTextureSize:gl.getParameter(gl.MAX_TEXTURE_SIZE),extensions:gl.getSupportedExtensions()}}),resources:performance.getEntriesByType('resource').map(r=>r.toJSON()),navigation:performance.getEntriesByType('navigation').map(r=>r.toJSON())}));fs.writeFileSync(path.join(out,label+'.json'),JSON.stringify(data,null,2));console.log('STATE',label,JSON.stringify({text:data.text,scroll:data.scroll,elements:data.elements,gl:data.gl}));}
 await state('desktop-entry');
 await page.mouse.move(720,450); await page.mouse.wheel(0,450);await page.waitForTimeout(1800); await page.screenshot({path:path.join(out,'desktop-03-wheel450.png')});await state('desktop-wheel450');
 for(let i=0;i<8;i++){await page.mouse.wheel(0,700);await page.waitForTimeout(1300);await page.screenshot({path:path.join(out,`desktop-scroll-${i+1}.png`)});}
 await state('desktop-scroll-end');
 fs.writeFileSync(path.join(out,'desktop-network.json'),JSON.stringify(requests,null,2));fs.writeFileSync(path.join(out,'desktop-console.json'),JSON.stringify(errors,null,2));fs.writeFileSync(path.join(out,'desktop-metrics.json'),JSON.stringify(await client.send('Performance.getMetrics'),null,2));
 await context.close();await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
